# In .rubocop.yml
# Make sure to exclude unused dirs or it'll run 10,000+ files in circleci
AllCops:
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "**/*.rake"

Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ModuleFunction:
  EnforcedStyle: 'extend_self'
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Performance/RedundantMerge:
  Enabled: false
