# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 933734a413b8825f77c2e73b121faa14bbe20c10bf8532bf0bccf20e8d107bd364b9d4a5c24e9d65d35af3b8e7b8beebfef97dd89efc0f7569e96ddfc7763c44
  hop_audience_key: 5036a27207cfdcfaa0417e4148efefb903a7d588363c8650b004c1f1a2f163948364c62749b3bebbc7125a68386c32d77da91e0dc0ac84cab225527952e4f38a
  encrypt_base64_key: <%= ENV["ENCRYPT_BASE64_KEY"] || "zhvy/fskdkdDmx3zFsDT97N6dByIy/8DxdruS9il6X/HDlDTXm9XyD8RZ3oPaRhGYUGErKLtlnsPbnbU/hVtsg==" %>
  bridge_pay: 'blr037test|57!sE@3Fm|758000|758001'
  aws: <%= ENV["AWS"] || 'IdString|SecretString|PoolString|IdentityString|RegionString|BucketString' %>
  twilio: "ACcab31cb5b9371e338d9f59d56828a459|e6959c3bd4934cd61f01f340a3a979f3|+15005550006"

test:
  secret_key_base: 3a1967c932eb2646e83fde87e64a905124c0d375930630a111b987fbe658036410a3a3157d1279183993c332efdd607579ae43655fa9ebd3bbe4099c4d9748e8
  hop_audience_key: 685332c5eb48dc24a3a407f7b134c181243f8c599cacb8b30a139eed8a8c454fe39fc5522e4d99827ab154731034b9d2bc30af56f12b8f8ce21f381b74091fad
  encrypt_base64_key: "zhvy/fskdkdDmx3zFsDT97N6dByIy/8DxdruS9il6X/HDlDTXm9XyD8RZ3oPaRhGYUGErKLtlnsPbnbU/hVtsg=="
  bridge_pay: 'blr037test|57!sE@3Fm|758000|758001'
  aws: 'IdString|SecretString|PoolString|IdentityString|RegionString|BucketString'
  twilio: "ACcab31cb5b9371e338d9f59d56828a459|e6959c3bd4934cd61f01f340a3a979f3|+15005550006"

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hop_audience_key: <%= ENV["HOP_AUDIENCE_KEY"] %>
  encrypt_base64_key: <%= ENV["ENCRYPT_BASE64_KEY"] %>
  bridge_pay: <%= ENV["BRIDGE_PAY"] %>
  aws: <%= ENV["AWS"] %>
  twilio: <%= ENV["TWILIO"] %>
